# Generated by Django 5.2.12 on 2026-03-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hks_workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='phone',
            field=models.CharField(blank=True, help_text='Direct contact number', max_length=15, null=True),
        ),
    ]
