# Generated by Django 5.2.12 on 2026-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('waste_type', models.CharField(choices=[('plastic', 'Plastic'), ('ewaste', 'E-Waste'), ('organic', 'Organic'), ('mixed', 'Mixed'), ('paper', 'Paper'), ('glass', 'Glass'), ('metal', 'Metal')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate per kg in INR', max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleanliness', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='1=Poor,5=Excellent')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('pending', 'Pending')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='paid', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
