# Generated by Django 5.2.12 on 2026-03-06 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hks_collections', '0001_initial'),
        ('hks_households', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='hks_households.household'),
        ),
    ]
