# Generated by Django 5.2.12 on 2026-03-06 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hks_collections', '0003_initial'),
        ('hks_households', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='worker_feedback',
            field=models.TextField(blank=True, help_text='Optional feedback text from household', null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='worker_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1-5 star rating by household', null=True),
        ),
        migrations.CreateModel(
            name='SkipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for which collection is to be skipped')),
                ('reason', models.TextField(blank=True)),
                ('payment_action', models.CharField(choices=[('defer', 'Defer to next month'), ('waive', 'Waive')], default='defer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_requests', to='hks_households.household')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
