# Generated by Django 5.2.12 on 2026-03-09 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hks_collections', '0004_collection_worker_feedback_collection_worker_rating_and_more'),
        ('hks_households', '0003_household_preferred_payment_household_upi_id'),
        ('hks_workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='feedback_attitude',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='feedback_cleanliness',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='feedback_punctuality',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='worker_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], help_text='1-4: Poor/Average/Good/Excellent', null=True),
        ),
        migrations.CreateModel(
            name='ExtraPickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('plastic', 'Plastic'), ('ewaste', 'E-Waste'), ('organic', 'Organic'), ('mixed', 'Mixed'), ('paper', 'Paper'), ('glass', 'Glass'), ('metal', 'Metal')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_pickup_requests', to='hks_households.household')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pickup_requests', to='hks_workers.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
