# Generated by Django 5.2.12 on 2026-03-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hks_collections', '0005_collection_feedback_attitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Rate per kg in INR (0 for flat-fee collection)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='collection',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Weight in kg (0 for flat-fee collection)', max_digits=6),
        ),
    ]
