# Generated by Django 5.2.12 on 2026-03-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hks_notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_ml',
            field=models.TextField(blank=True, default='', help_text='Malayalam translation of message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('collection', 'Collection Confirmation'), ('payment', 'Payment Confirmation'), ('reminder', 'Collection Reminder'), ('broadcast', 'Admin Broadcast'), ('pickup', 'Extra Pickup Request'), ('feedback', 'Worker Feedback'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
