# Generated by Django 5.2.12 on 2026-03-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hks_households', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='preferred_payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='household',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Household UPI ID for payment', max_length=100, null=True),
        ),
    ]
