# Generated by Django 5.2.12 on 2026-03-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hks_households', '0003_household_preferred_payment_household_upi_id'),
        ('hks_wards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='hks_wards.ward'),
        ),
    ]
